// swift-tools-version: 6.0
import Foundation
import PackageDescription

// A manifest cannot see the build configuration, so the profile arrives as an
// environment variable. Hard-coding target/debug would silently link a debug
// core into a release app; `scripts/build.sh` sets this for both.
let rustProfile = ProcessInfo.processInfo.environment["ZER0_RUST_PROFILE"] ?? "debug"

let libraryDirectory = URL(fileURLWithPath: #filePath)
    .deletingLastPathComponent()
    .deletingLastPathComponent()
    .appendingPathComponent("target")
    .appendingPathComponent(rustProfile)
    .path

// The Rust half has run under `-D warnings` since the first commit: clippy is
// invoked from `scripts/check.sh` with it, and a warning there is a failed
// build. The Swift half ran on defaults, which meant the two languages in this
// repo had different definitions of "green" — on the half that also carries the
// UI, where an unused result or a deprecated API is exactly the kind of thing
// that is true for months before anyone reads the log.
//
// `-warnings-as-errors` is the flag rather than `.treatAllWarningsAs(.error)`
// because the latter needs swift-tools-version 6.2, and the manifest already
// reaches for `.unsafeFlags` for the same reason a step lower down.
//
// Applied to the shell, the entry point and the tests, and deliberately *not*
// to `Zer0Core`: that target is uniffi's generated output, regenerated by
// `scripts/build-core.sh` on every build, and failing a build over a warning
// in a file nobody writes would only teach people to delete this line.
let strict: [SwiftSetting] = [.unsafeFlags(["-warnings-as-errors"])]

let package = Package(
    name: "Zer0",
    // WKWebExtension, and therefore Chrome extension support, is macOS 15.4+.
    platforms: [.macOS("15.4")],
    dependencies: [
        // Auto-updater. ADR-0109 decided Sparkle 2 over 3 (more stable, better
        // documented) with one appcast per channel, both signed with one EdDSA
        // key. The version floor matches the one the ADR landed against; bumps
        // are deliberate, not transitive.
        .package(url: "https://github.com/sparkle-project/Sparkle.git", from: "2.7.0"),
    ],
    targets: [
        // Header + modulemap emitted by uniffi-bindgen.
        .systemLibrary(name: "Zer0CoreFFI", path: "Sources/Zer0CoreFFI"),

        // The generated Swift API, linked against the Rust staticlib.
        .target(
            name: "Zer0Core",
            dependencies: ["Zer0CoreFFI"],
            path: "Sources/Zer0Core",
            linkerSettings: [
                .unsafeFlags([
                    "-L\(libraryDirectory)",
                    "-lzer0_core",
                ])
            ]
        ),

        // The browser itself. Kept as a library so it can be driven by tests
        // without launching an app.
        .target(
            name: "Zer0Shell",
            dependencies: ["Zer0Core", .product(name: "Sparkle", package: "Sparkle")],
            path: "Sources/Zer0Shell",
            swiftSettings: strict
        ),

        // Thin entry point: everything real lives in Zer0Shell.
        .executableTarget(
            name: "Zer0",
            dependencies: ["Zer0Shell"],
            path: "Sources/Zer0",
            swiftSettings: strict
        ),

        .testTarget(
            name: "Zer0ShellTests",
            dependencies: ["Zer0Shell"],
            path: "Tests/Zer0ShellTests",
            swiftSettings: strict
        ),
    ]
)
